export const Progression = {
    AGREE_TO_LEGAL: 1,
    SYSTEM_CHECK: 2,
    INSTRUCTIONS: 3,
    INTERVIEW_BEGUN: 4,
    INTERVIEW_COMPLETE: 5,
    INTERVIEW_SUBMITTED: 6,
    INTERVIEW_SUBMIT_FAILED: 7
}